config/routes.rb
Youtubeservice::Application.routes.draw do
  resources :yslygis

  resources :offers

  resources :categories

  resources :admins

  get "index/index"

  get "index/destroy_user"
  
  get "/me", to: "index#me"

  post "/index/createyslyga/:id", to: "index#createyslyga"

  get "/sponsors", to: "index#sponsors"

  get "/sponsors/details/:id", to: "index#sponsorsdetails"

  get "/yslygaapplycreate/:id", to: "index#yslygaapplycreate"
  
  post "/index/searchingProfile", to: "index#searchingProfile"
  
  get "/index/logout"
  
  get "index/start"

  get "index/registration"

  get "search", to: "index#search"

  get "category/:id", to: "index#category"

  get "/index/searchingCheckbox"
  
  get "/profile/:id", to: "index#profile"

  get "/offer", to: "index#offers"

  get "/createoffer", to: "index#createoffer"
  
  get "admin", to: "index#admin"

  post "/index/createofferpost"

  get '/youtube/auth', to: "index#getyoutubeauth"

  get '/index/wait_new_user', to: "index#wait_new_user"

  get "/editoffer/:id", to: "index#editoffer"

  get "/destroyoffer/:id", to: "index#destroyoffer"

  get "/offer/details/:id", to: "index#offerdetails"

  put "/index/:id/updateoffer", to: "index#updateoffer"

  get "/collabration", to: "index#collabration"

  get "/offerapplycreate/:id", to: "index#offerapplycreate"

  get "/offers/applicants/:id", to: "index#applicants"

  post "/index/createtopic/:id", to: "index#createtopic"
  
  get "/directmessages", to: "index#directmessages"

  get "/topic/:id", to: "index#topic"

  post "/index/createmessage/:id", to: "index#createmessage"

  get "/account", to: "index#account"

  put "/index/:id/update_account", to: "index#update_account"
  
  post "index/checkAdmin"

  post "index/create"

  resources :textdescs

  resources :users

  root :to=>"index#index"

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing admins</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password digest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.email %></td>
    <td><%= admin.password_digest %></td>
    <td><%= link_to 'Show', admin %></td>
    <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
    <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @admin.password_digest %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>