config/routes.rb
Youtubeservice::Application.routes.draw do
  resources :yslygis

  resources :offers

  resources :categories

  resources :admins

  get "index/index"

  get "index/destroy_user"
  
  get "/me", to: "index#me"

  post "/index/createyslyga/:id", to: "index#createyslyga"

  get "/sponsors", to: "index#sponsors"

  get "/sponsors/details/:id", to: "index#sponsorsdetails"

  get "/yslygaapplycreate/:id", to: "index#yslygaapplycreate"
  
  post "/index/searchingProfile", to: "index#searchingProfile"
  
  get "/index/logout"
  
  get "index/start"

  get "index/registration"

  get "search", to: "index#search"

  get "category/:id", to: "index#category"

  get "/index/searchingCheckbox"
  
  get "/profile/:id", to: "index#profile"

  get "/offer", to: "index#offers"

  get "/createoffer", to: "index#createoffer"
  
  get "admin", to: "index#admin"

  post "/index/createofferpost"

  get '/youtube/auth', to: "index#getyoutubeauth"

  get '/index/wait_new_user', to: "index#wait_new_user"

  get "/editoffer/:id", to: "index#editoffer"

  get "/destroyoffer/:id", to: "index#destroyoffer"

  get "/offer/details/:id", to: "index#offerdetails"

  put "/index/:id/updateoffer", to: "index#updateoffer"

  get "/collabration", to: "index#collabration"

  get "/offerapplycreate/:id", to: "index#offerapplycreate"

  get "/offers/applicants/:id", to: "index#applicants"

  post "/index/createtopic/:id", to: "index#createtopic"
  
  get "/directmessages", to: "index#directmessages"

  get "/topic/:id", to: "index#topic"

  post "/index/createmessage/:id", to: "index#createmessage"

  get "/account", to: "index#account"

  put "/index/:id/update_account", to: "index#update_account"
  
  post "index/checkAdmin"

  post "index/create"

  resources :textdescs

  resources :users

  root :to=>"index#index"

end

app/models/yslygi.rb
#coding:UTF-8
class Yslygi < ActiveRecord::Base
  attr_accessible :category, :date, :description, :name, :user_id, :to_topic
  OFFERS_ARRAY_CATEGORY=[
  						["Интеграция бренда/продукта в ваши видео", "brand_product_integration"],
  						["Отзывы о продуктах", "product_reviews"],
  						["Выделенное количество видео про бренд", "dedicated_videos"],
  						["Продвижение вне YouTube(сайт, соц. сети)", "offyoutube_promotion"],
  						["Добавление видео про бренд/продукт в плейлист", "including_brand_videos"],
              ["Обмен лайками", "obmen_like_yslyga"],
              ["Реклама о вас моем ролике","reklama_v_rolike_yslyga"],
  						["Открыт к другим видам услуг", "open_to_other_types_sponsor"]
  						]

  validates :name, :description, :category, format:{with: /[[:graph:]]/, message: "Поле заполнено неверно"}
  validates :date, format:{with: /^([0-9]{2}\/){2}[0-9]{4}$/, message: "Формат: ДД/ММ/ГГГГ"}

end

app/controllers/yslygis_controller.rb
class YslygisController < ApplicationController
  # GET /yslygis
  # GET /yslygis.json
  def index
    @yslygis = Yslygi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @yslygis }
    end
  end

  # GET /yslygis/1
  # GET /yslygis/1.json
  def show
    @yslygi = Yslygi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @yslygi }
    end
  end

  # GET /yslygis/new
  # GET /yslygis/new.json
  def new
    @yslygi = Yslygi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yslygi }
    end
  end

  # GET /yslygis/1/edit
  def edit
    @yslygi = Yslygi.find(params[:id])
  end

  # POST /yslygis
  # POST /yslygis.json
  def create
    @yslygi = Yslygi.new(params[:yslygi])

    respond_to do |format|
      if @yslygi.save
        format.html { redirect_to @yslygi, notice: 'Yslygi was successfully created.' }
        format.json { render json: @yslygi, status: :created, location: @yslygi }
      else
        format.html { render action: "new" }
        format.json { render json: @yslygi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /yslygis/1
  # PUT /yslygis/1.json
  def update
    @yslygi = Yslygi.find(params[:id])

    respond_to do |format|
      if @yslygi.update_attributes(params[:yslygi])
        format.html { redirect_to @yslygi, notice: 'Yslygi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @yslygi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yslygis/1
  # DELETE /yslygis/1.json
  def destroy
    @yslygi = Yslygi.find(params[:id])
    @yslygi.destroy

    respond_to do |format|
      format.html { redirect_to yslygis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/yslygis_helper.rb
module YslygisHelper
end

app/views/yslygis/_form.html.erb
<%= form_for(@yslygi) do |f| %>
  <% if @yslygi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yslygi.errors.count, "error") %> prohibited this yslygi from being saved:</h2>

      <ul>
      <% @yslygi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yslygis/edit.html.erb
<h1>Editing yslygi</h1>

<%= render 'form' %>

<%= link_to 'Show', @yslygi %> |
<%= link_to 'Back', yslygis_path %>

app/views/yslygis/index.html.erb
<h1>Listing yslygis</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Category</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @yslygis.each do |yslygi| %>
  <tr>
    <td><%= yslygi.name %></td>
    <td><%= yslygi.description %></td>
    <td><%= yslygi.category %></td>
    <td><%= yslygi.date %></td>
    <td><%= link_to 'Show', yslygi %></td>
    <td><%= link_to 'Edit', edit_yslygi_path(yslygi) %></td>
    <td><%= link_to 'Destroy', yslygi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Yslygi', new_yslygi_path %>

app/views/yslygis/new.html.erb
<h1>New yslygi</h1>

<%= render 'form' %>

<%= link_to 'Back', yslygis_path %>

app/views/yslygis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @yslygi.name %>
</p>

<p>
  <b>Description:</b>
  <%= @yslygi.description %>
</p>

<p>
  <b>Category:</b>
  <%= @yslygi.category %>
</p>

<p>
  <b>Date:</b>
  <%= @yslygi.date %>
</p>


<%= link_to 'Edit', edit_yslygi_path(@yslygi) %> |
<%= link_to 'Back', yslygis_path %>