config/routes.rb
Youtubeservice::Application.routes.draw do
  resources :yslygis

  resources :offers

  resources :categories

  resources :admins

  get "index/index"

  get "index/destroy_user"
  
  get "/me", to: "index#me"

  post "/index/createyslyga/:id", to: "index#createyslyga"

  get "/sponsors", to: "index#sponsors"

  get "/sponsors/details/:id", to: "index#sponsorsdetails"

  get "/yslygaapplycreate/:id", to: "index#yslygaapplycreate"
  
  post "/index/searchingProfile", to: "index#searchingProfile"
  
  get "/index/logout"
  
  get "index/start"

  get "index/registration"

  get "search", to: "index#search"

  get "category/:id", to: "index#category"

  get "/index/searchingCheckbox"
  
  get "/profile/:id", to: "index#profile"

  get "/offer", to: "index#offers"

  get "/createoffer", to: "index#createoffer"
  
  get "admin", to: "index#admin"

  post "/index/createofferpost"

  get '/youtube/auth', to: "index#getyoutubeauth"

  get '/index/wait_new_user', to: "index#wait_new_user"

  get "/editoffer/:id", to: "index#editoffer"

  get "/destroyoffer/:id", to: "index#destroyoffer"

  get "/offer/details/:id", to: "index#offerdetails"

  put "/index/:id/updateoffer", to: "index#updateoffer"

  get "/collabration", to: "index#collabration"

  get "/offerapplycreate/:id", to: "index#offerapplycreate"

  get "/offers/applicants/:id", to: "index#applicants"

  post "/index/createtopic/:id", to: "index#createtopic"
  
  get "/directmessages", to: "index#directmessages"

  get "/topic/:id", to: "index#topic"

  post "/index/createmessage/:id", to: "index#createmessage"

  get "/account", to: "index#account"

  put "/index/:id/update_account", to: "index#update_account"
  
  post "index/checkAdmin"

  post "index/create"

  resources :textdescs

  resources :users

  root :to=>"index#index"

end

app/models/textdesc.rb
class Textdesc < ActiveRecord::Base
  attr_accessible :name, :text
end

app/controllers/textdescs_controller.rb
class TextdescsController < ApplicationController
  # GET /textdescs
  # GET /textdescs.json
  def index
    @textdescs = Textdesc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @textdescs }
    end
  end

  # GET /textdescs/1
  # GET /textdescs/1.json
  def show
    @textdesc = Textdesc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @textdesc }
    end
  end

  # GET /textdescs/new
  # GET /textdescs/new.json
  def new
    @textdesc = Textdesc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @textdesc }
    end
  end

  # GET /textdescs/1/edit
  def edit
    @textdesc = Textdesc.find(params[:id])
  end

  # POST /textdescs
  # POST /textdescs.json
  def create
    @textdesc = Textdesc.new(params[:textdesc])

    respond_to do |format|
      if @textdesc.save
        format.html { redirect_to @textdesc, notice: 'Textdesc was successfully created.' }
        format.json { render json: @textdesc, status: :created, location: @textdesc }
      else
        format.html { render action: "new" }
        format.json { render json: @textdesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /textdescs/1
  # PUT /textdescs/1.json
  def update
    @textdesc = Textdesc.find(params[:id])

    respond_to do |format|
      if @textdesc.update_attributes(params[:textdesc])
        format.html { redirect_to @textdesc, notice: 'Textdesc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @textdesc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /textdescs/1
  # DELETE /textdescs/1.json
  def destroy
    @textdesc = Textdesc.find(params[:id])
    @textdesc.destroy

    respond_to do |format|
      format.html { redirect_to textdescs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/textdescs_helper.rb
module TextdescsHelper
end

app/views/textdescs/_form.html.erb
<%= form_for(@textdesc) do |f| %>
  <% if @textdesc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@textdesc.errors.count, "error") %> prohibited this textdesc from being saved:</h2>

      <ul>
      <% @textdesc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/textdescs/edit.html.erb
<h1>Editing textdesc</h1>

<%= render 'form' %>

<%= link_to 'Show', @textdesc %> |
<%= link_to 'Back', textdescs_path %>

app/views/textdescs/index.html.erb
<h1>Listing textdescs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @textdescs.each do |textdesc| %>
  <tr>
    <td><%= textdesc.name %></td>
    <td><%= textdesc.text %></td>
    <td><%= link_to 'Show', textdesc %></td>
    <td><%= link_to 'Edit', edit_textdesc_path(textdesc) %></td>
    <td><%= link_to 'Destroy', textdesc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Textdesc', new_textdesc_path %>

app/views/textdescs/new.html.erb
<h1>New textdesc</h1>

<%= render 'form' %>

<%= link_to 'Back', textdescs_path %>

app/views/textdescs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @textdesc.name %>
</p>

<p>
  <b>Text:</b>
  <%= @textdesc.text %>
</p>


<%= link_to 'Edit', edit_textdesc_path(@textdesc) %> |
<%= link_to 'Back', textdescs_path %>